package frc.robot.subsystems.shooter;

/**
 * Constants for swerve drive subsystem.
 * Generated by Thrifty Swerve Generator.
 * Generated on: 2025-07-17T22:32:29.693Z
 */
public final class HoodConstants {
  public static final Double MAX_ANGLE_DEGREES = 90.0;
  public static final Double MIN_ANGLE_DEGREES = 0.0; // Degrees.of(0);
}
