package frc.robot.subsystems.drivetrain;

import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.util.Units;

/**
 * Constants for swerve drive subsystem.
 * Generated by Thrifty Swerve Generator.
 * Generated on: 2026-01-31T15:50:01.528Z
 */
public final class SwerveConstants {
  // Drive base dimensions
  public static final double DRIVE_BASE_WIDTH_METERS = 0.7365996022362148;
  public static final double DRIVE_BASE_LENGTH_METERS = 0.6349996571001851;

  // Gear ratios
  public static final double DRIVE_GEAR_RATIO = 6.23;
  public static final double AZIMUTH_GEAR_RATIO = 25;

  // Wheel specifications
  public static final double WHEEL_DIAMETER_INCHES = 4;
  public static final double WHEEL_DIAMETER_METERS = Units.inchesToMeters(4);

  // Top Speed (calculated from motor free speed, wheel diameter & gear ratio)
  public static final double TOP_SPEED_MOTOR_RPM = 6000;
  public static final double TOP_SPEED_METERS_PER_SEC =
      TOP_SPEED_MOTOR_RPM * WHEEL_DIAMETER_METERS * Math.PI / DRIVE_GEAR_RATIO / 60; // = 5.123 m/s

  // Module locations from center of robot
  private static final double HALF_WIDTH = DRIVE_BASE_WIDTH_METERS / 2.0;
  private static final double HALF_LENGTH = DRIVE_BASE_LENGTH_METERS / 2.0;

  // Kinematics
  public static final Translation2d FRONT_LEFT_LOCATION =
      new Translation2d(HALF_LENGTH, HALF_WIDTH);
  public static final Translation2d FRONT_RIGHT_LOCATION =
      new Translation2d(HALF_LENGTH, -HALF_WIDTH);
  public static final Translation2d BACK_LEFT_LOCATION =
      new Translation2d(-HALF_LENGTH, HALF_WIDTH);
  public static final Translation2d BACK_RIGHT_LOCATION =
      new Translation2d(-HALF_LENGTH, -HALF_WIDTH);

  public static final SwerveDriveKinematics DRIVE_KINEMATICS = new SwerveDriveKinematics(
      FRONT_LEFT_LOCATION, FRONT_RIGHT_LOCATION, BACK_LEFT_LOCATION, BACK_RIGHT_LOCATION);

  // Encoder type enum - MUST be defined before ModuleConstants
  public static enum EncoderType {
    REDUX_ENCODER,
    SRX_MAG_ENCODER,
    REV_ENCODER,
    THRIFTY_ABSOLUTE_ENCODER,
    THRIFTY_10PIN_ENCODER,
    THRIFTY_ANALOG_ENCODER
  }

  public static enum GyroType {
    NAVX,
    PIGEON2,
    CANANDGYRO,
    NONE
  }

  // Module constants
  public static final class ModuleConstants {
    // Front Left Module
    public static final int FRONT_LEFT_DRIVE_MOTOR_ID = 3;
    public static final int FRONT_LEFT_AZIMUTH_MOTOR_ID = 4;
    public static final double FRONT_LEFT_ENCODER_OFFSET =
        1354; // 2661;//2741; // Encoder offset in ticks
    public static final boolean FRONT_LEFT_DRIVE_MOTOR_INVERTED = false;
    public static final boolean FRONT_LEFT_AZIMUTH_MOTOR_INVERTED = false;
    public static final int FRONT_LEFT_ANALOG_ENCODER_CHANNEL = 0;
    public static final boolean FRONT_LEFT_ANALOG_ENCODER_INVERTED = false;

    // Front Right Module
    public static final int FRONT_RIGHT_DRIVE_MOTOR_ID = 5;
    public static final int FRONT_RIGHT_AZIMUTH_MOTOR_ID = 6;
    public static final double FRONT_RIGHT_ENCODER_OFFSET = 2095; // 139; // Encoder offset in ticks
    public static final boolean FRONT_RIGHT_DRIVE_MOTOR_INVERTED = false;
    public static final boolean FRONT_RIGHT_AZIMUTH_MOTOR_INVERTED = false;
    public static final int FRONT_RIGHT_ANALOG_ENCODER_CHANNEL = 0;
    public static final boolean FRONT_RIGHT_ANALOG_ENCODER_INVERTED = false;

    // Back Left Module
    public static final int BACK_LEFT_DRIVE_MOTOR_ID = 1;
    public static final int BACK_LEFT_AZIMUTH_MOTOR_ID = 2;
    public static final double BACK_LEFT_ENCODER_OFFSET =
        2559; // 3170-2048; // Encoder offset in ticks
    public static final boolean BACK_LEFT_DRIVE_MOTOR_INVERTED = false;
    public static final boolean BACK_LEFT_AZIMUTH_MOTOR_INVERTED = false;
    public static final int BACK_LEFT_ANALOG_ENCODER_CHANNEL = 0;
    public static final boolean BACK_LEFT_ANALOG_ENCODER_INVERTED = false;

    // Back Right Module
    public static final int BACK_RIGHT_DRIVE_MOTOR_ID = 7;
    public static final int BACK_RIGHT_AZIMUTH_MOTOR_ID = 8;
    public static final double BACK_RIGHT_ENCODER_OFFSET = 1823; // 3794; // Encoder offset in ticks
    public static final boolean BACK_RIGHT_DRIVE_MOTOR_INVERTED = false;
    public static final boolean BACK_RIGHT_AZIMUTH_MOTOR_INVERTED = false;
    public static final int BACK_RIGHT_ANALOG_ENCODER_CHANNEL = 0;
    public static final boolean BACK_RIGHT_ANALOG_ENCODER_INVERTED = false;

    // Selected encoder type
    public static final EncoderType ENCODER_SELECTED = EncoderType.THRIFTY_10PIN_ENCODER;
    public static final double ENCODER_TICKS_PER_ROTATION = 4096;
  }

  // Gyro constants
  public static final class GyroConstants {
    public static final GyroType GYRO_TYPE = GyroType.NAVX; // NAVX;
    public static final Object[] GYRO_PARAMS = new Object[] {}; // No parameters needed for NavX
  }
}
