/* Generated by Phoenix Tuner X */
package frc.robot.subsystems.led;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.RainbowAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.subsystems.shooter.ShooterSubsystem;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDSubsystem extends SubsystemBase {
  private final CANdle m_candle = new CANdle(18, CANBus.roboRIO());
  Trigger brownoutTrigger = new Trigger(RobotController::isBrownedOut);

  private final RainbowAnimation m_slot0Animation = new RainbowAnimation(0, 38)
      .withSlot(0)
      .withBrightness(1)
      .withDirection(AnimationDirectionValue.Forward)
      .withFrameRate(Hertz.of(100));

  private final SolidColor m_green = new SolidColor(0, 38).withColor(new RGBWColor(13, 255, 1, 0));
  private final SolidColor m_red = new SolidColor(0, 38).withColor(new RGBWColor(255, 20, 20, 0));

  public LEDSubsystem() {
    setDefaultCommand(updateLEDs());
    m_candle.clearAllAnimations();
    brownoutTrigger.whileTrue(startRun(
            () -> {
              m_candle.clearAllAnimations();
            },
            () -> {
              m_candle.setControl(m_red);
            })
        .ignoringDisable(true));
  }

  @Override
  public void periodic() {
    SmartDashboard.putBoolean("isCandleConnected", m_candle.isConnected());
  }

  public Command rainbow() {
    return run(() -> {
          m_candle.clearAllAnimations();
          m_candle.setControl(m_slot0Animation);
        })
        .ignoringDisable(true);
  }

  public Command green() {
    return run(() -> {
          m_candle.clearAllAnimations();
          m_candle.setControl(m_green);
        })
        .ignoringDisable(true);
  }

  public Command showREVCommand(ShooterSubsystem shooter) {
    return startRun(
            () -> {
              m_candle.clearAllAnimations();
            },
            () -> {
              double rev = shooter.getRevPrecentage();
              if (rev >= 90) {
                m_candle.setControl(m_slot0Animation);
              }  else if (rev >= 70) {
                m_candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(200, 0, 255, 20)));
              } else if (rev >= 45) {
                m_candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(255, 120, 0, 20)));
              } else {
                m_candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(0, 100, 255, 20)));
              }
            })
        .ignoringDisable(true);
  }

  public Command showOuttakeCommand() {
    return startRun(() -> {
        m_candle.clearAllAnimations();
    }, () -> {
        m_candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(255, 110, 180, 40)));
    });
  }

  /**
   * Updates the animations and LEDs of the CANdle.
   *
   * @return Command to run
   */
  public Command updateLEDs() {
    return run(() -> {
          m_candle.clearAllAnimations();
          m_candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(10, 255, 10, 30)));
        })
        .ignoringDisable(true);
  }
}
