/* Generated by Phoenix Tuner X */
package frc.robot.subsystems.led;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.FireAnimation;
import com.ctre.phoenix6.controls.RainbowAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.subsystems.indexer.IndexerSubsystem;
import frc.robot.subsystems.shooter.ShooterSubsystem;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDSubsystem extends SubsystemBase {
  private static final CANdle candle = new CANdle(18, CANBus.roboRIO());
  // private final Trigger brownoutTrigger = new Trigger(RobotController::isBrownedOut);

  private enum LEDState {
    NONE,
    DEFAULT_GREEN,
    REV_LOW,
    REV_MID,
    REV_HIGH,
    SHOOTING_RAINBOW,
    OUTTAKE_FIRE,
    ALIGN_PINK,
    BROWNOUT
  }

  private LEDState currentState = LEDState.NONE;

  private final RainbowAnimation rainbowAnimation = new RainbowAnimation(0, 38)
      .withSlot(0)
      .withBrightness(1)
      .withDirection(AnimationDirectionValue.Forward)
      .withFrameRate(Hertz.of(150));

  private final FireAnimation leftFireAnimation = new FireAnimation(8, 23)
      .withSlot(1)
      .withDirection(AnimationDirectionValue.Backward)
      .withFrameRate(Hertz.of(200));

  private final FireAnimation rightFireAnimation = new FireAnimation(24, 38)
      .withSlot(2)
      .withDirection(AnimationDirectionValue.Forward)
      .withFrameRate(Hertz.of(200));

  public LEDSubsystem() {
    // brownoutTrigger.whileTrue(
    //    startRun(() -> setLEDState(LEDState.BROWNOUT), () -> setLEDState(LEDState.BROWNOUT))
    //        .ignoringDisable(true));
  }

  @Override
  public void periodic() {
    SmartDashboard.putBoolean("isCandleConnected", candle.isConnected());
  }

  private void setLEDState(LEDState newState) {
    if (currentState == newState) {
      return;
    }
    currentState = newState;
    candle.clearAllAnimations();

    switch (newState) {
      case DEFAULT_GREEN:
        candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(10, 255, 10, 30)));
        break;
      case REV_LOW:
        candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(0, 100, 255, 20)));
        break;
      case REV_MID:
        candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(255, 120, 0, 20)));
        break;
      case REV_HIGH:
        candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(200, 0, 255, 20)));
        break;
      case SHOOTING_RAINBOW:
        candle.setControl(rainbowAnimation);
        break;
      case OUTTAKE_FIRE:
        candle.setControl(leftFireAnimation);
        candle.setControl(rightFireAnimation);
        break;
      case BROWNOUT:
        candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(255, 20, 20, 0)));
        break;
      case ALIGN_PINK:
        candle.setControl(new SolidColor(0, 38).withColor(new RGBWColor(255, 182, 193, 20)));
        break;
      case NONE:
      default:
        break;
    }
  }

  public Command showREVCommand(ShooterSubsystem shooter, IndexerSubsystem indexer) {
    return run(() -> {
      double rev = shooter.getRevPrecentage();
      boolean shoot = indexer.isKickerRunningForward();
      if (shoot && !indexer.isPreloading) {
        setLEDState(LEDState.SHOOTING_RAINBOW);
      } else if (rev >= 75) {
        setLEDState(LEDState.REV_HIGH);
      } else if (rev >= 32) {
        setLEDState(LEDState.REV_MID);
      } else {
        setLEDState(LEDState.REV_LOW);
      }
    });
  }

  public Command showOuttakeCommand() {
    return startRun(() -> setLEDState(LEDState.OUTTAKE_FIRE), () -> {});
  }

  public Command updateLEDs() {
    return run(() -> setLEDState(LEDState.DEFAULT_GREEN)).ignoringDisable(true);
  }

  public Command updateLEDs(Trigger align) {
    return run(() ->
            setLEDState(align.getAsBoolean() ? LEDState.ALIGN_PINK : LEDState.DEFAULT_GREEN))
        .ignoringDisable(true);
  }
}
